tbcng/Models/cat.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbcng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat
    {
        public cat()
        {
            this.cats1 = new HashSet<cat>();
            this.products = new HashSet<product>();
        }
    
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public string cat_url { get; set; }
        public Nullable<int> cat_pos { get; set; }
        public Nullable<int> cat_parent_id { get; set; }
    
        public virtual ICollection<cat> cats1 { get; set; }
        public virtual cat cat1 { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}

tbcng/Controllers/CatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tbcng.Models;
using tbcng.Helpers;
using System.Threading.Tasks;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;

namespace tbcng.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class CatsController : Controller
    {
        private thietbicnEntities db = new thietbicnEntities();

        public ActionResult List(int? pg, string search)
        {
            int pageSize = 25;
            if (pg == null) pg = 1;
            int pageNumber = (pg ?? 1);
            ViewBag.pg = pg;
            var data = db.cats.Where(x => x.cat_parent_id != null);
            if (data == null)
            {
                return View(data);
            }
            if (!string.IsNullOrWhiteSpace(search))
            {
                search = search.Trim();
                data = data.Where(x => x.cat_name.ToLower().Contains(search));
                ViewBag.search = search;
            }

            data = data.OrderBy(x => x.cat_pos);
            return View(data.ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: Cats
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(CatVM model)
        {
            if (!ModelState.IsValid)
            {
                TempData["Errored"] = "Vui lòng kiểm tra lại các trường.";
                return RedirectToRoute("AdminAddCat");
            }

            try
            {
                cat _new = new cat();
                _new.cat_name = model.cat_name ?? null;
                _new.cat_parent_id = model.cat_parent_id ?? null;
                _new.cat_url = _new.cat_name != null ? configs.unicodeToNoMark(_new.cat_name) : null;
                _new.cat_pos = model.cat_pos ?? null;
                db.cats.Add(_new);
                await db.SaveChangesAsync();

                TempData["Updated"] = "Thêm danh mục thành công";
                return RedirectToRoute("AdminAddCat");
            }

            catch (Exception ex)
            {
                ModelState.AddModelError("", "Có lỗi xảy ra khi thêm danh mục mới");
                configs.SaveTolog(ex.ToString());
                return View(model);
            }

        }

        public async Task<ActionResult> Edit(int? id)
        {

            if (id == null || id == 0 || id == 1)
            {
                return RedirectToRoute("Admin");
            }
            cat _cat = await db.cats.FindAsync(id);
            if (_cat == null)
            {
                return View(_cat);
            }
            var getCat = new CatVM()
            {
                cat_id = _cat.cat_id,
                cat_name = _cat.cat_name,
                cat_parent_id = _cat.cat_parent_id,
                cat_pos = _cat.cat_pos
            };

            ViewBag.TenCat = _cat.cat_name;
            return View(getCat);
        }


        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CatVM model)
        {
            if (!ModelState.IsValid)
            {
                TempData["Errored"] = "Vui lòng kiểm tra lại các trường.";
                return RedirectToRoute("AdminEditCat", new { id = model.cat_id });
            }
            try
            {
                var _cat = await db.cats.FindAsync(model.cat_id);
                if (_cat != null)
                {
                    _cat.cat_name = model.cat_name ?? null;
                    _cat.cat_parent_id = model.cat_parent_id ?? null;
                    _cat.cat_pos = model.cat_pos ?? null;
                    _cat.cat_url = _cat.cat_name != null ? configs.unicodeToNoMark(_cat.cat_name) : null;
                    db.Entry(_cat).State = System.Data.Entity.EntityState.Modified;
                    await db.SaveChangesAsync();
                    TempData["Updated"] = "Cập nhật danh mục thành công";
                }
                return RedirectToRoute("AdminListCat");
            }
            catch (Exception ex)
            {
                TempData["Errored"] = "Có lỗi xảy ra khi cập nhật danh mục.";
                configs.SaveTolog(ex.ToString());
                return RedirectToRoute("AdminEditCat", new { id = model.cat_id });
            }

        }

        public ActionResult Delete(int? id)
        {
            if (id == null || id == 0 || id == 1)
            {
                return RedirectToRoute("Admin");
            }
            cat _cat = db.cats.Find(id);
            if (_cat == null)
            {
                return View();
            }
            return View(_cat);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            cat _cat = await db.cats.FindAsync(id);
            if (_cat == null)
            {
                return View();
            }
            if (_cat.cats1.Count() > 0)
            {
                TempData["Error"] = "Bạn không thể xóa danh mục này. <br /> Danh mục này chứa danh mục con khác. Vui lòng xóa danh mục con trước.";
                return RedirectToRoute("AdminDeleteCat", new { id = _cat.cat_id });
            }
            try
            {
                db.cats.Remove(_cat);
                await db.SaveChangesAsync();
                TempData["Deleted"] = "Danh mục đã được xóa khỏi danh sách.";
            }
            catch (Exception ex)
            {
                configs.SaveTolog(ex.ToString());
            }

            return RedirectToRoute("AdminListCat");
        }

        public PartialViewResult lstCatPartial()
        {
            List<LstCat> data = db.cats.Select(x => new LstCat()
            {
                CatId = x.cat_id,
                CatName = x.cat_name,
                ParentCatId = x.cat_parent_id,
                CatPos = x.cat_pos,
                CatURL = x.cat_url
            }).OrderBy(x => x.CatPos).ToList();

            var presidents = data.Where(x => x.ParentCatId == null).FirstOrDefault();
            SetChildrenCat(presidents, data);
            return PartialView("_lstCatPartial", presidents);
        }

        private void SetChildrenCat(LstCat model, List<LstCat> danhmuc)
        {
            var childs = danhmuc.Where(x => x.ParentCatId == model.CatId).ToList();
            if (childs.Count > 0)
            {
                foreach (var child in childs)
                {
                    SetChildrenCat(child, danhmuc);
                    model.LstCats.Add(child);
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

tbcng/Views/Cats/Add.cshtml
@using tbcng.Models
@model CatVM
@{
    ViewBag.Title = "Thêm danh mục";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section PageTitleHeader {
    <div class="page-header">
        <h3><i class="fa fa-list fa-2x fa-color-red"></i> @ViewBag.Title</h3>
    </div>
    @if (TempData["Updated"] != null)
    {
        <div class="alert alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            @Html.Raw(TempData["Updated"])
        </div>
    }
    @if (TempData["Errored"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            @Html.Raw(TempData["Errored"])
        </div>
    }
}

@* form_add_new_cat *@
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default box box-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Vui lòng nhập đầy đủ các trường có dấu <span class="color-red">(*)</span></h3>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Add", "Cats", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", role = "form", @id = "add-new-cat" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.cat_name, htmlAttributes: new { @class = "control-label col-md-2 required-after" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.cat_name, htmlAttributes: new { @class = "form-control", placeholder = "Nhập tên danh mục" })
                            @Html.ValidationMessageFor(model => model.cat_name, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.cat_parent_id, htmlAttributes: new { @class = "control-label col-md-2 required-after" })
                        <div class="col-md-8">
                            @Html.HiddenFor(m => m.cat_parent_id)
                            @{ Html.RenderAction("lstCatPartial", "Cats"); }
                            @Html.ValidationMessageFor(model => model.cat_parent_id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.cat_pos, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.cat_pos, htmlAttributes: new { @class = "form-control", placeholder = "Nhập vị trí danh mục", type = "number" })
                            @Html.ValidationMessageFor(model => model.cat_pos, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-primary">
                                <i class="fa fa-plus color-white"></i> Thêm mới
                            </button>
                        </div>
                    </div>

                }


            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        //$.validator.setDefaults({
        //    ignore: []
        //});

        $(function () {
            $(document).ready(function () {
                $("#add-new-cat").data("validator").settings.ignore = "";
                // code here this
                $('#cat_parent').on('change', function () {
                    if ($(this).val() !== "") {
                        $('#cat_parent_id').val($(this).val());
                    } else {
                        $('#cat_parent_id').val('');
                    }
                })

            });
        });
    </script>

}

tbcng/Views/Cats/Delete.cshtml
@using tbcng.Models
@model cat
@{
    ViewBag.Title = "Xóa danh mục";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section PageTitleHeader {
    <div class="page-header">
        <h3><i class="fa fa-list fa-2x fa-color-red"></i> @ViewBag.Title</h3>
    </div>

    @if (TempData["Errored"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            @Html.Raw(TempData["Errored"])
        </div>

    }

    @if (TempData["Deleted"] != null)
    {
        <div class="alert alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            @Html.Raw(TempData["Deleted"])
        </div>
    }
}


@if (Model != null)
{

    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default box box-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Bạn chắc chắn muốn xóa danh mục <b>@Html.DisplayFor(m => m.cat_name)?</b></h3>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @*<input type="submit" class="btn btn-primary" value="Xóa menu" />*@
                        <button class="btn btn-danger" id="confirmdelete"><i class="fa fa-trash"></i> Xóa</button>
                        <span class="btn btn-default" onclick="gotoUrl('@Url.RouteUrl("AdminListCat")')"><i class="fa fa-close"></i> Hủy xóa</span>
                    }
                </div>
            </div>
        </div>
    </div>

}
else
{
    <span>Không tìm thấy menu.</span>
}

@section Scripts {

    <script>
        $(document).ready(function () {
            $('#confirmdelete').on('click', function (e) {
                confirmDelete(e);
            })
        })
    </script>
}

tbcng/Views/Cats/Edit.cshtml
@using tbcng.Models
@model CatVM
@{
    ViewBag.Title = "Sửa danh mục bài viết";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section PageTitleHeader {
    <div class="page-header">
        <h3><i class="fa fa-list fa-2x fa-color-red"></i> @ViewBag.Title</h3>
    </div>
    @if (TempData["Updated"] != null)
    {
        <div class="alert alert-success alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            @Html.Raw(TempData["Updated"])
        </div>
    }

    @if (TempData["Errored"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            @Html.Raw(TempData["Errored"])
        </div>
    }
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default box box-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Sửa menu <b>@ViewBag.TenCat</b></h3>
            </div>
            @if (Model != null)
            {
                <div class="panel-body">
                    @using (Html.BeginForm("Edit", "Cats", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", role = "form", @id = "form-edit-cat" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(m => m.cat_id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.cat_name, htmlAttributes: new { @class = "control-label col-md-2 required-after" })
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.cat_name, htmlAttributes: new { @class = "form-control", placeholder = "Nhập tên danh mục" })
                                @Html.ValidationMessageFor(model => model.cat_name, "", new { @class = "text-danger" })
                            </div>

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.cat_parent_id, htmlAttributes: new { @class = "control-label col-md-2 required-after" })
                            <div class="col-md-8">
                                @Html.HiddenFor(m => m.cat_parent_id)
                                @{ Html.RenderAction("lstCatPartial", "Cats"); }
                                @Html.ValidationMessageFor(model => model.cat_parent_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <script>
                        window.onload = function () {
                            if (document.getElementById('cat_parent_id').value !== "") {
                                document.getElementById('cat_parent').value = document.getElementById('cat_parent_id').value;
                            }
                        }
                        </script>

                        <div class="form-group">
                            @Html.LabelFor(model => model.cat_pos, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.cat_pos, htmlAttributes: new { @class = "form-control", placeholder = "Nhập vị trí danh mục", type = "number" })
                                @Html.ValidationMessageFor(model => model.cat_pos, "", new { @class = "text-danger" })
                            </div>

                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button class="btn btn-primary"><i class="fa fa-edit"></i> Cập nhật</button>
                                <span class="btn btn-danger" onclick="gotoUrl('@Url.RouteUrl("AdminDeleteCat", new { id = Model.cat_id })')"><i class="fa fa-trash"></i> Xóa</span>
                            </div>
                        </div>

                    }


                </div>
            }


        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $.validator.setDefaults({
            ignore: []
        });

        $(function () {
            $(document).ready(function () {
                
                // code here this
                $('#cat_parent').on('change', function () {
                    console.log($(this).val());
                    if ($(this).val() !== "") {
                        $('#cat_parent_id').val($(this).val());
                    } else {
                        $('#cat_parent_id').val('');
                    }
                })

            });
        });
    </script>
}

tbcng/Views/Cats/List.cshtml
@model PagedList.IPagedList<tbcng.Models.cat>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh mục bài viết";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section Styles {
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/admin/vendor/datatable/dataTables.bootstrap.min.css" rel="stylesheet" />
}

<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h3>@ViewBag.Title <span class="btn btn-primary pull-right" onclick="gotoUrl('@Url.RouteUrl("AdminAddCat")')"><i class="fa fa-plus"></i> Thêm mới menu</span></h3>
        </div>
        @if (TempData["Deleted"] != null)
        {
            <div class="alert alert-success alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                @Html.Raw(TempData["Deleted"])
            </div>
        }

        @if (TempData["Updated"] != null)
        {
            <div class="alert alert-success alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                @Html.Raw(TempData["Updated"])
            </div>
        }

    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default box box-primary">
            <div class="panel-heading">
                @using (Html.BeginForm("List", "Cats", FormMethod.Get, new { @class = "form-inline", role = "form", @id = "search-cats", onsubmit = "return validate()" }))
                {
                    <div class="form-group">
                        <label for="searchQuery" class="control-label">Tìm kiếm: </label>
                        @Html.TextBox("search", "", new { @class = "form-control", placeholder = "Nhập tên danh mục" })
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary"><i class="fa fa-search"></i>Tìm kiếm</button>
                    </div>
                }
            </div>

            <script>
                function validate() {
                    if (document.getElementById("search").value === "") {
                        alert('Vui lòng nhập từ khóa tìm kiếm');
                        return false;
                    } else {
                        return true;
                    };
                }
            </script>

            <div class="panel-body">

                <div class="table-responsive">
                    <table class="table table-bordered table-striped table_order_stt" id="table-cats">
                        <thead>
                            <tr>
                                <th class="no-sort" style="width: 50px; text-align: center;">Số TT</th>
                                <th style="width: 200px;">Tên danh mục</th>
                                <th style="width: 200px;">Danh mục cha</th>
                                <th>Vị trí</th>
                                <th style="width: 144px;" class="no-sort"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                if (Model.Count > 0)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td style="text-align: center;"></td>
                                            <td>@item.cat_name</td>
                                            <td>
                                                @if (item.cat1 != null)
                                                {
                                                    if (item.cat1.cat_name == "danhmuc")
                                                    { <text>là danh mục cha</text> }
                                                    else
                                                    { @item.cat1.cat_name }
                                                }
                                            </td>
                                            <td>@item.cat_pos</td>

                                            <td>
                                                <span class="btn btn-primary" onclick="gotoUrl('@Url.RouteUrl("AdminEditCat", new { id = item.cat_id })')"><i class="fa fa-edit"></i> Sửa</span>
                                                <span class="btn btn-danger" onclick="gotoUrl('@Url.RouteUrl("AdminDeleteCat", new { id = item.cat_id })')"><i class="fa fa-trash"></i> Xóa</span>
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="6">
                                            Chưa có danh mục nào
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="6">
                                        Không có danh mục
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                @if (Model != null)
                {
                    @Html.PagedListPager(Model, page => Url.RouteUrl("AdminListCat", new { search = ViewBag.search, pg = page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
                }

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Content/admin/vendor/datatable/jquery.dataTables.min.js"></script>
    <script src="~/Content/admin/vendor/datatable/dataTables.bootstrap.min.js"></script>
    <script>

        $(document).ready(function () {
            $('#table-cats').DataTable({
                paging: false,
                "oLanguage": {
                    "sEmptyTable": "Không tìm thấy danh mục nào.",
                    "sLoadingRecords": "Vui lòng - chờ...",
                    "sSearch": "Tìm kiếm nhanh: ",
                    "sZeroRecords": "Không tìm thấy danh mục nào.",
                    "sInfo": ""
                },
                "order": [],
                columnDefs: [
                    { targets: 'no-sort', orderable: false }
                ]
            });
        });

    </script>
}

tbcng/Views/Cats/_childCatPartial.cshtml
@using tbcng.Models
@model LstCat
@foreach (var item in Model.LstCats)
{
    if (item != null)
    {
        <option value="@item.CatId" class="@if (item.LstCats.Count > 0) {@Html.DisplayName("font-w-bold")} else {}">
            @if (item.LstCats.Count > 0)
            {@Html.DisplayName("--")}
            else { }@item.CatName
        </option>
    
        if (item.LstCats.Count > 0)
        {
            @Html.Partial("_childCatPartial", item)
        }
        
    }
}

tbcng/Views/Cats/_lstCatPartial.cshtml
@using tbcng.Models
@model LstCat
<select class="form-control width-200" id="cat_parent">
    <option value="">--Chọn danh mục cha--</option>
    <option value="1">--Danh mục cha--</option>
    @Html.Partial("_childCatPartial", @Model)
</select>